# Generated by Django 4.0.4 on 2022-05-19 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
